# Generated by Django 5.0 on 2025-10-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="petition",
            name="votes",
            field=models.IntegerField(default=0),
        ),
    ]
