# Generated by Django 5.0 on 2025-10-14 18:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petition", "0003_petitionvote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="petitionvote",
            unique_together={("petition", "user")},
        ),
    ]
