# Generated by Django 5.0 on 2025-09-05 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_item"),
        ("movies", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="movie",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.movie",
            ),
            preserve_default=False,
        ),
    ]
